// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbKac812Kgn6W_ABu2mdYTSUyPA3Y32hU',
    appId: '1:623442523846:web:353dc6df1754050aab89c7',
    messagingSenderId: '623442523846',
    projectId: 'c204-f0d54',
    authDomain: 'c204-f0d54.firebaseapp.com',
    storageBucket: 'c204-f0d54.appspot.com',
    measurementId: 'G-SDFKKB3K0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADdbNk2dHKPyPZwBHPoOXsmD8DGcu-OoQ',
    appId: '1:623442523846:android:3f6a1ca9163e2fb0ab89c7',
    messagingSenderId: '623442523846',
    projectId: 'c204-f0d54',
    storageBucket: 'c204-f0d54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz6IsEAV3szN_RFgy3hxb8FzTVoSRnAD0',
    appId: '1:623442523846:ios:68e9e4fa92b0d041ab89c7',
    messagingSenderId: '623442523846',
    projectId: 'c204-f0d54',
    storageBucket: 'c204-f0d54.appspot.com',
    iosBundleId: 'com.example.ll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbKac812Kgn6W_ABu2mdYTSUyPA3Y32hU',
    appId: '1:623442523846:web:227c40cdfc85985dab89c7',
    messagingSenderId: '623442523846',
    projectId: 'c204-f0d54',
    authDomain: 'c204-f0d54.firebaseapp.com',
    storageBucket: 'c204-f0d54.appspot.com',
    measurementId: 'G-KYJMBH7B8H',
  );
}
